### ISSUE TITLE
Stratum1 data location

### ISSUE THREAD

**Issue by jpecar** [EESSI/filesystem-layer#100]
While deploying stratum1 system I learned that its data actually ends up in /srv. 
`roles/galaxyproject.cvmfs/defaults/main.yml` actually offers to handle `cvmfs_srv_device` and `cvmfs_srv_mount` but it's commented out by default. Would be nice if a sentence in docs points to that setting so one can properly set it up before first ansible run fills up root partition ;)

**Comment by bedroge** [comment]
This has been addressed in the docs, so I'm closing this issue.
