### ISSUE TITLE
Changed symlink does not trigger a publish

### ISSUE THREAD

**Issue by ocaisa** [EESSI/filesystem-layer#123]
In https://github.com/EESSI/filesystem-layer/blob/main/roles/create_cvmfs_content_structure/tasks/do_repo.yml#L35 (introduced in https://github.com/EESSI/filesystem-layer/pull/118) there's an expectation that files _and_ symlinks must have changed to publish a transaction (and symlinks appear to always "change" due to https://github.com/EESSI/filesystem-layer/blob/main/roles/create_cvmfs_content_structure/tasks/do_repo.yml#L18 ...but I don't know Ansible at all).

In https://github.com/EESSI/filesystem-layer/pull/115 however, we only change a symlink and this does not get published as the file change criteria is not matched. The symlinks thing should perhaps not be forced (but there is probably a reason it is), and then [the other condition](https://github.com/EESSI/filesystem-layer/blob/main/roles/create_cvmfs_content_structure/tasks/do_repo.yml#L35) can be changed to:
```
      - create_symlinks.changed or create_files.changed
```

**Comment by zilverberg** [comment]
It seems the force is needed when the you want to create the symlink eventhough the source doesnt exists.
This is probably needed for the symlink: host_injections -> '$(EESSI_HOST_INJECTIONS:-/opt/eessi)'

http://www.freekb.net/Article?id=179

**Comment by ocaisa** [comment]
Ah ok, so this probably means that `create_symlinks.changed` is _not_ always true (the force is there for another reason). In that case the change above is definitely required since files will certainly change without symlink changes

**Comment by zilverberg** [comment]
As I read it the force only triggers when the source doesnt exists or when the destination does but is a file.
Therefore the change to an or statement should work.

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html

**Comment by zilverberg** [comment]
testing confirms this.
PR created: https://github.com/EESSI/filesystem-layer/pull/124
