### ISSUE TITLE
git cvmfs-layer.git  - Error

### ISSUE THREAD

**Issue by JvD007** [EESSI/filesystem-layer#13]
By using the following command, I got a Permission denied message
$ git clone --recursive git@github.com:EESSI/cvmfs-layer.git

gives the following message:
Permission denied (publickey).
fatal: Could not read from remote repository.

$ git clone https://github.com/EESSI/cvmfs-layer.git

Works fine

**Comment by bedroge** [comment]
This happens in case you haven't added a public SSH key to your Github account. Using https in the instructions is probably better, so this has been changed in #14.
