### ISSUE TITLE
remove 2021.06 version from pilot EESSI CVMFS repo

### ISSUE THREAD

**Issue by boegel** [EESSI/filesystem-layer#140]
Since we're no longer making changes to the 2021.06 pilot version, we should remove `/cvmfs/pilot.eessi-hpc.org/2021.06`.

No objections were raised against this in the EESSI Slack or in today's EESSI update meeting.

We should "archive" the contents of `/cvmfs/pilot.eessi-hpc.org/2021.06` though.
The easiest way (for now) would be to just create tarballs, perhaps separate for the different CPU families `x86_64`, `aarch64`, `ppc64le`)

**Comment by bedroge** [comment]
I've created tarballs of the `2021.06` stack (one per CPU family), and uploaded them to the AWS bucket `eessi-archive`. An announcement of the removal has been sent to the mailing list and slack, so without any objection I'll remove it from the repo next week. As @ocaisa proposed in #141, we could replace the `2021.06` directory by a symlink to something like `/cvmfs/pilot.eessi-hpc.org/host_injections/versions/2021.06`?

**Comment by ocaisa** [comment]
Maybe we should make a new symlink `archive` that operates the same as `host_injections`

**Comment by ocaisa** [comment]
Since an archive is likely to be pretty large, it might be a better approach to separate it from `host_injections` rather than force them into the same location

**Comment by bedroge** [comment]
Yeah, that's perhaps more appropriate than `host_injections`. Do we want to set a default path for the variant symlink (e.g. `/opt/eessi/archive`?)?

**Comment by bedroge** [comment]
By the way, `2021.06` was originally built/installed to `/cvmfs/pilot.eessi-hpc.org/2021.06` (without `versions`, which was added later on), and we now have a symlink `versions/2021.06 -> 2021.06`. I would really like to get rid of that `2021.06` dir in the root of the repo, but not having it anymore would mean that stuff could/will break... So I guess we really do have to keep it, maybe until we switch to the new `eessi.io` domain/repo?

**Comment by boegel** [comment]
Plan:

1) Remove 2021.06

```
rm -rf /cvmfs/pilot.eessi-hpc.org/2021.06
rm /cvmfs/pilot.eessi-hpc.org/versions/2021.06
```

2) Create replacement init scripts for 2021.06

cfr. https://github.com/EESSI/software-layer/pull/246

```
mkdir -p /cvmfs/pilot.eessi-hpc.org/versions/2021.06/init/
cp -a software-layer/versions/2021.06/init/* /cvmfs/pilot.eessi-hpc.org/versions/2021.06/init/
```

**Comment by bedroge** [comment]
This was done by printing a deprecation message and automatically loading `2021.12`, see: https://github.com/EESSI/software-layer/tree/main/versions/2021.06/init.
