### ISSUE TITLE
Filesystem requirements

### ISSUE THREAD

**Issue by JvD007** [EESSI/filesystem-layer#15]
What are the requirements for installing the stratum0/1 

Is it only ansable
We need also Open SSH server and client on the server.
Do we need more?

Got some ssh errors when I was running "ansible-playbook -i hosts -b -K stratum1.yml"

**Comment by bedroge** [comment]
Ansible should be the only thing you need. Since Ansible needs to be able to log in to the remote server(s) that you want to configure, you do indeed need OpenSSH on those machines. I can make a small note about this in the README.
