### ISSUE TITLE
BECOME password - running stratum1.yml

### ISSUE THREAD

**Issue by JvD007** [EESSI/filesystem-layer#16]
When I run $ ansible-playbook -i hosts -b -K stratum1.yml it's asking me to enter the password for BECOME

BECOME password:  <is not in the README>

I don't see any information around this account or did I miss something?

**Comment by JvD007** [comment]
Problem solved by adding -u <user> --ask-pass 

[Test was on ubuntu 16.04] Not supported for the moment?

**Comment by bedroge** [comment]
The "become" is used for privilege escalation, i.e. to run certain things as root / with sudo. So, the become password is your sudo password. This is explained a bit here:
https://github.com/EESSI/filesystem-layer#running-the-playbooks

If you can do passwordless sudo, you can leave out the -b flag.
