### ISSUE TITLE
Stratum 1 on CentOS 8 installation messages 

### ISSUE THREAD

**Issue by JvD007** [EESSI/filesystem-layer#17]
running the playbook without an user:

Error:
root@stratum filesystem-layer]# ansible-playbook -i hosts -b -K stratum1.yml
BECOME password: 

PLAY [CVMFS Stratum 1] *************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************
fatal: [stratum.home.local]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@stratum.home.local: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).", "unreachable": true}

PLAY RECAP *************************************************************************************************************************************
stratum.home.local         : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0  

Running the playbook with u <user>.
[root@stratum filesystem-layer]# ansible-playbook -i hosts -b -K stratum1.yml -u dell --ask-pass
SSH password: 
BECOME password[defaults to SSH password]: 

PLAY [CVMFS Stratum 1] *************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************
ok: [stratum.home.local]

TASK [geerlingguy.repo-epel : Check if EPEL repo is already configured.] ***********************************************************************
ok: [stratum.home.local]

TASK [geerlingguy.repo-epel : Install EPEL repo.] **********************************************************************************************
skipping: [stratum.home.local]

TASK [geerlingguy.repo-epel : Import EPEL GPG key.] ********************************************************************************************
skipping: [stratum.home.local]

TASK [geerlingguy.repo-epel : Disable Main EPEL repo.] *****************************************************************************************
skipping: [stratum.home.local]

TASK [cvmfs : Set OS-specific variables] *******************************************************************************************************
ok: [stratum.home.local]

TASK [cvmfs : Set facts for Galaxy CVMFS config repository, if enabled] ************************************************************************
ok: [stratum.home.local]

TASK [cvmfs : Set facts for Galaxy CVMFS static repositories, if enabled] **********************************************************************
skipping: [stratum.home.local]

TASK [cvmfs : Set facts for CVMFS config repository, if enabled] *******************************************************************************
ok: [stratum.home.local]

TASK [cvmfs : include_tasks] *******************************************************************************************************************
skipping: [stratum.home.local]

TASK [cvmfs : include_tasks] *******************************************************************************************************************
included: /root/Downloads/filesystem-layer/roles/cvmfs/tasks/stratum1.yml for stratum.home.local

TASK [cvmfs : Include initial OS-specific tasks] ***********************************************************************************************
included: /root/Downloads/filesystem-layer/roles/cvmfs/tasks/init_redhat.yml for stratum.home.local

TASK [cvmfs : Configure CernVM yum repositories] ***********************************************************************************************
ok: [stratum.home.local] => (item={'name': 'cernvm', 'description': 'CernVM packages', 'baseurl': 'http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs/EL/$releasever/$basearch/'})
ok: [stratum.home.local] => (item={'name': 'cernvm-config', 'description': 'CernVM-FS extra config packages', 'baseurl': 'http://cvmrepo.web.cern.ch/cvmrepo/yum/cvmfs-config/EL/$releasever/$basearch/'})

TASK [cvmfs : Install CernVM yum key] **********************************************************************************************************
ok: [stratum.home.local]

TASK [cvmfs : Install CernVM-FS packages and dependencies (yum)] *******************************************************************************
fatal: [stratum.home.local]: FAILED! => {"changed": false, "failures": ["No package mod_wsgi available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

PLAY RECAP *************************************************************************************************************************************
stratum.home.local         : ok=9    changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0  

Running the playbook with -vvv
gives more info aroun the modules, but with module do we need installed before we run the playbook

fatal: [stratum.home.local]: FAILED! => {
    "changed": false,
    "failures": [
        "No package mod_wsgi available."
    ],
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "autoremove": false,
            "bugfix": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_dir": null,
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 30,
            "name": [
                "httpd",
                "mod_wsgi",
                "squid",
                "cvmfs-server",
                "cvmfs-config-default"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "present",
            "update_cache": false,
            "update_only": false,
            "validate_certs": true
        }
    },
    "msg": "Failed to install some of the specified packages",
    "rc": 1,
    "results": []
}

Any info is welcome

The test script for wsgi works fine, which module do we need here?

**Comment by JvD007** [comment]
In CentOS 8 mod_wsgi  is now only available in python3-mod_wsgi in  RHEL 8.0 -  The mod_wsgi module for the Apache  HTTP Server has been updated to Python 3. WSGI applications are now  supported only with Python 3, and must be migrated from Python 2.

We are now using Python2 is that correct?

**Comment by JvD007** [comment]
For CentOS8 and RedHat 8 change the following in the file **redhat.yml**. Located in the directory, <your-folder>/filesystem-layer/roles/cvmfs/vars/

Change entry **mod_wsgi to python3-mod_wsgi**

Run playbook with:

$ **ansible-playbook -i hosts -b -K stratum1.yml -u dell --ask-pass -e 'ansible_python_interpreter=/usr/bin/python3' -vvv**

Works fine, _got now errors on the connection to stratum0 - root issue on the stratum0_

**Comment by bedroge** [comment]
Yes, I guess this is by default still using Python 2 on for instance CentOS 7 (which I mostly used for testing). I'll take a look at this, we probably need to send a PR to the Galaxy project to get this fixed.
