### ISSUE TITLE
staging PR for EasyBuild installation in zen4 + updated archspec file didn't show full overview of tarball contents

### ISSUE THREAD

**Issue by boegel** [EESSI/filesystem-layer#190]
see https://github.com/EESSI/staging/pull/1235 (note: private repo), which was used for deploying both the changes from https://github.com/EESSI/software-layer/pull/451 + https://github.com/EESSI/software-layer/pull/547

Only `2023.06/init/arch_specs/eessi_arch_x86.spec` is shown in overview of tarball contents, the EasyBuild installation + module file located in `2023.06/software/linux/x86_64/amd/zen4/software` was not included for some reason...

Those files *are* listed in the overview produced by the bot though, see https://github.com/EESSI/software-layer/pull/547#issuecomment-2098040799

**Comment by bedroge** [comment]
The code for generating the overview only works well for tarballs that only contain software, see:
https://github.com/EESSI/filesystem-layer/blob/main/scripts/automated_ingestion/eessitarball.py#L99
In this case the tarball also included init files from the root of the repo, and then the `os.path.commonprefix` doesn't work anymore.

But maybe we can easily reuse the same code that the bot uses to produce a tarball overview.

**Comment by boegel** [comment]
should be fixed by #195, so closing...
