### ISSUE TITLE
Symlinks for "latest" and "preview" stacks

### ISSUE THREAD

**Issue by ocaisa** [EESSI/filesystem-layer#51]
It would be nice to have a `latest` (-> `2020.10` right now) symlink in `/cvmfs/pilot.eessi-hpc.org/` so that we don't need to continuously update scripts. This will also facilitate integration in other tools like Magic Castle.

Having a `preview` symlink for the next iteration of the stack would also be useful.

**Comment by ocaisa** [comment]
The other thing required for Magic Castle integration is the path to the python3 installation for the stack which is required to configure JupyterHub properly. Unfortunately it is a chicken/egg situation so I wrote a script that can live in the `init` directory to make the path static (and probably looks very familiar):
```
#!/usr/bin/env sh
EESSI_PILOT_VERSION="2020.10"
EESSI_PREFIX=/cvmfs/pilot.eessi-hpc.org/$EESSI_PILOT_VERSION

if [ -d $EESSI_PREFIX ]; then
  EPREFIX=$EESSI_PREFIX/compat/$(uname -m)
  if [ -d $EPREFIX ]; then
    # determine subdirectory in software layer
    # note: eessi_software_subdir_for_host.py will pick up value from $EESSI_SOFTWARE_SUBDIR_OVERRIDE if it's defined!
    EESSI_PYTHON=$EPREFIX/usr/bin/python3
    EESSI_SOFTWARE_SUBDIR=$($EESSI_PYTHON ${EESSI_PREFIX}/init/eessi_software_subdir_for_host.py $EESSI_PREFIX)
    if [ ! -z $EESSI_SOFTWARE_SUBDIR ]; then
        EESSI_SOFTWARE_PATH=$EESSI_PREFIX/software/$EESSI_SOFTWARE_SUBDIR
        if [ -d $EESSI_SOFTWARE_PATH ]; then
          eessi_pilot_python=$(ls ${EESSI_SOFTWARE_PATH}/software/Python/3*/bin/python | sed 1q)
          if [ -f "$eessi_pilot_python" ]; then
            $eessi_pilot_python "$@"
          else
            echo "ERROR: No EESSI pilot python 3 available."
            false
          fi
        else
          echo "ERROR: EESSI software layer at $EESSI_SOFTWARE_PATH not found!" >&2
          false
        fi
    else
        echo "ERROR: no value set for \$EESSI_SOFTWARE_SUBDIR" >&2
        false
    fi
  else
    echo "ERROR: Compatibility layer directory %s not found!" >&2
    false
  fi
else
  echo "ERROR: EESSI pilot repository at $EESSI_PREFIX not found!" >&2
  false
fi
```

**Comment by bedroge** [comment]
I like the idea, though I was wondering if this will always work. By loading software through the symlink (`latest`), it's basically being run from a different location than where it was installed. In principle that could cause issues, but, on the other hand, the original installation directory (e.g. `2020.10`) is also available. So I guess that software with hardcoded paths should still work in that case (?).

**Comment by ocaisa** [comment]
This is just an end-user convenience, and the real reason I want this is to give me an easy way to way to access the latest bash initialisation script. That bash script is path independent (it has a hardcoded `EESSI_PILOT_VERSION`) and points to the correct software stage and modules path which are the things which actually affect the software environment.

People trying to run software through the symlink is going to be problematic since they would need the path info (that the initialisation script gives you) as well as wildcards for the software version. And even then it will still probably work because of the rpathing.

**Comment by bedroge** [comment]
Ah, right, then it should definitely work indeed.

**Comment by bedroge** [comment]
Done!

```
$ ls /cvmfs/pilot.eessi-hpc.org/ -l
total 10
drwxr-xr-x 6 cvmfs cvmfs 4096 okt  1 13:13 2020.09
drwxr-xr-x 5 cvmfs cvmfs 4096 nov  4 18:02 2020.10
lrwxrwxrwx 1 cvmfs cvmfs    7 nov 25 11:25 latest -> 2020.10
```

**Comment by ocaisa** [comment]
Excellent, thanks @bedroge !

**Comment by bedroge** [comment]
We could even make it a variant symlink, which would allow us to change the symlink with a configuration parameter (e.g. `EESSI_LATEST_VERSION`) in the cvmfs-config repo, or anyone else by changing their local CVMFS configuration.
https://cvmfs.readthedocs.io/en/stable/cpt-repo.html#variant-symlinks

But I guess a regular symlink is good enough for now.

**Comment by boegel** [comment]
@bedroge Did you just create that symlink manually? Should we get this covered in the Ansible playbooks as well? I think we should...

**Comment by bedroge** [comment]
Yes, for now I created this manually. I don't think it really fits well in the existing playbooks (the only one that would make a bit of sense is `stratum0-deploy-cvmfs-config.yml`), so maybe we should put in a new one (e.g. `stratum0-set-latest-symlink.yml`?) which takes the `latest` value from our configuration file?

On the other hand,  is not really a filesystem-layer configuration item, so maybe this is yet another example where a more global configuration file (as @terjekv proposed) would make sense.

**Comment by ocaisa** [comment]
I also really liked the variant symlink idea, I think that would be really useful for a `production` symlink which would allow sites to stick on once EESSI version until they are ready to move on (like if they needed to build custom software on top of the new layer)

**Comment by boegel** [comment]
@bedroge So we need a separate `config` repo? Or `global-config`?

Should we re-open this issue until that's in place?

**Comment by bedroge** [comment]
I think just `config` is fine. Or maybe `eessi-config` (though `EESSI/eessi-config` might be a bit double).

**Comment by boegel** [comment]
W.r.t. the config stuff: how about a `config` subdirectory in [EESSI/infrastructure](https://github.com/EESSI/infrastructure)?

**Comment by terjekv** [comment]
What would we store in the config directory? Some version mapping (latest, production, testing?)? Global CVMFS-details (nodes etc?)
