### ISSUE TITLE
Document the CVMFS config.

### ISSUE THREAD

**Issue by terjekv** [EESSI/filesystem-layer#53]
The contents of our `cvmfs-config-eessi-`packages are good to have, but some people (like on Mac) may want to create the config themselves. Or do we want to offer a pkg?

**Comment by bedroge** [comment]
The tool that we use to build the packages (fpm) does support that, I think, so we could try to build a client package for Mac.

**Comment by terjekv** [comment]
Pretty please? I'm testing CVMFS right now. :) Once that's done I'll build a combat layer for the path we decide on.

**Comment by bedroge** [comment]
Nevertheless, we should document how to configure the repositories manually, especially for people that already have a different `cvmfs-config-*` package installed. Unfortunately, you can only have one...

**Comment by bedroge** [comment]
Closed by #54.
