### ISSUE TITLE
add EESSI configuration to cvmfs-contrib/config-repo

### ISSUE THREAD

**Issue by boegel** [EESSI/filesystem-layer#58]
We should consider adding the necessary EESSI configuration files to https://github.com/cvmfs-contrib/config-repo (as discussed during today's CernVM-FS coordination meeting).

They also provide a yum repository, see https://cvmfs-contrib.github.io/ 

cc @bedroge

**Comment by boegel** [comment]
Relevant docs update: https://github.com/cvmfs/doc-cvmfs/pull/156

**Comment by bedroge** [comment]
This was done in https://github.com/cvmfs-contrib/config-repo/pull/206.
