### ISSUE TITLE
(Re)configure garbage collection / automatic tagging

### ISSUE THREAD

**Issue by bedroge** [EESSI/filesystem-layer#61]
Our playbook currently enables garbage collection (`CVMFS_GARBAGE_COLLECTION=true` + cronjobs), but also automatic tagging (`CVMFS_AUTO_TAG=true`). However, those tags never got cleaned up. I manually changed this for now by setting setting a retention period using `CVMFS_AUTO_TAG_TIMESPAN="2 weeks ago`.

Especially for our production repo we should think about what kind of garbage collection (there's also a `CVMFS_AUTO_GC`) and automatic tagging (can also be disabled completely) we want.

**Comment by rptaylor** [comment]
We disable CVMFS_AUTO_GC so that it does not get triggered by snapshots or publishing and just use a nightly cron `cvmfs_server gc -a -l -f` instead.

Auto tags are useful, I recommend keeping that, and we use `CVMFS_AUTO_TAG_TIMESPAN="30 days ago"`.

**Comment by bedroge** [comment]
Useful information, thanks! Our current setup seems to be quite similar. I'll check if this works as expected now, and then we can add it to our Ansible files.

**Comment by bedroge** [comment]
This still didn't seem to work properly on our Stratum 0, but I just found that it was because `/var/log/cvmfs` didn't exist. This should be added to the Ansible role that we use.
