### ISSUE TITLE
Provide tarball with client configuration

### ISSUE THREAD

**Issue by bedroge** [EESSI/filesystem-layer#68]

**Comment by akesandgren** [comment]
I suggest doing what CC do in their config.d/xxx.conf, add this at the end for quicker testing.

# if CVMFS_HTTP_PROXY is undefined or empty, use DIRECT
if [ "x$CVMFS_HTTP_PROXY" = "x" ]; then
  CVMFS_HTTP_PROXY="DIRECT"
fi

**Comment by rptaylor** [comment]
We use fpm to produce the client config packages,  RPM, deb, tzip, tgz ,  and many more, all in one.
I can share the script if you want, it's quite simple.
The artifacts produced go here: https://package.computecanada.ca/yum/cc-cvmfs-public/prod/other/
